name: Build Develop

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clean and build debug version of app
        run: ./gradlew clean assembleDebug
